<?php
session_start();
require_once 'php/Database.php';
require_once 'php/User.php';
require_once 'php/Jobs.php';

// If the user is not logged in or is not an employer, redirect them.
if (!isset($_SESSION['user_id']) || $_SESSION['user_type'] !== 'employer') {
    header('Location: login.html');
    exit();
}

$job_id = isset($_GET['job_id']) ? intval($_GET['job_id']) : 0;

if (empty($job_id)) {
    header('Location: manage-jobs.php');
    exit();
}

$database = new Database();
$db = $database->getConnection();
$jobs = new Jobs($db);
$job = $jobs->getJobById($job_id);

// Check if the job exists and belongs to the current user
if (!$job || $job['employer_id'] !== $_SESSION['user_id']) {
    header('Location: manage-jobs.php');
    exit();
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Applicants for <?php echo htmlspecialchars($job['title']); ?></title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/kanban.css">
</head>

<body>
    <button class="sidebar-toggle">
        <i class="fas fa-bars"></i>
    </button>
    <div class="dashboard-wrapper">
        <?php include 'includes/sidebar.php'; ?>
        <main class="dashboard-content">
            <h1 class="h3 mb-4">Job Posting: Applicants for <?php echo htmlspecialchars($job['title']); ?></h1>
            <div id="kanban-board" class="kanban-board">
                <!-- Columns will be dynamically generated by JavaScript -->
            </div>
        </main>
    </div>

    <!-- Schedule Interview Modal -->
    <div class="modal fade" id="scheduleInterviewModal" tabindex="-1" aria-labelledby="scheduleInterviewModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="scheduleInterviewModalLabel">Schedule Interview</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="scheduleInterviewForm">
                        <input type="hidden" id="applicationId" name="application_id">
                        <input type="hidden" id="applicantId" name="job_seeker_id">
                        <div class="mb-3">
                            <label for="interview_datetime" class="form-label">Interview Date and Time</label>
                            <input type="datetime-local" class="form-control" id="interview_datetime"
                                name="interview_datetime" required>
                        </div>
                        <div class="mb-3">
                            <label for="notes" class="form-label">Notes (optional)</label>
                            <textarea class="form-control" id="notes" name="notes" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Send Invitation</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Send Email Modal -->
    <div class="modal fade" id="sendEmailModal" tabindex="-1" aria-labelledby="sendEmailModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="sendEmailModalLabel">Send Rejection Email</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="sendEmailForm">
                        <input type="hidden" id="emailApplicationId" name="application_id">
                        <div class="mb-3">
                            <label for="email_template" class="form-label">Select a Template</label>
                            <select class="form-select" id="email_template" name="email_template">
                                <option value="">Custom Email</option>
                                <option value="rejection_1">Rejection Template 1</option>
                                <option value="rejection_2">Rejection Template 2</option>
                                <option value="rejection_3">Rejection Template 3</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="email_subject" class="form-label">Subject</label>
                            <input type="text" class="form-control" id="email_subject" name="subject" required>
                            <div id="profanity-warning-subject" class="form-text text-danger" style="display: none;">
                                Inappropriate language detected.</div>
                        </div>
                        <div class="mb-3">
                            <label for="email_body" class="form-label">Body</label>
                            <textarea class="form-control" id="email_body" name="body" rows="5" required></textarea>
                            <div id="profanity-warning-body" class="form-text text-danger" style="display: none;">
                                Inappropriate language detected.</div>
                        </div>
                        <button type="submit" class="btn btn-primary">Send Email</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Cover Letter Modal -->
    <div class="modal fade" id="coverLetterModal" tabindex="-1" aria-labelledby="coverLetterModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="coverLetterModalLabel">Cover Letter</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p id="coverLetterContent"></p>
                </div>
            </div>
        </div>
    </div>

    <!-- Screening Answers Modal -->
    <div class="modal fade" id="screeningAnswersModal" tabindex="-1" aria-labelledby="screeningAnswersModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="screeningAnswersModalLabel">Screening Answers</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="screeningAnswersContent">
                    <!-- Answers will be loaded here by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.14.0/Sortable.min.js"></script>
    <script src="js/dashboard.js"></script>
    <script>
        const jobId = <?php echo json_encode($job_id); ?>;
    </script>
    <script src="js/view-applicants.js"></script>
</body>

</html>